// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz6cGibO3WvXXrxQ_MRvzDw2_2e46yXWg',
    appId: '1:218821411512:web:98bf446b564cd3ab24ea4d',
    messagingSenderId: '218821411512',
    projectId: 'mychatapp-522bc',
    authDomain: 'mychatapp-522bc.firebaseapp.com',
    storageBucket: 'mychatapp-522bc.appspot.com',
    measurementId: 'G-1PGRFHN6PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiIfxI2Vnp6A_x4LotEmL-fZjJZGWctkg',
    appId: '1:218821411512:android:3f7a3328dd73241f24ea4d',
    messagingSenderId: '218821411512',
    projectId: 'mychatapp-522bc',
    storageBucket: 'mychatapp-522bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwf8QOxJmZO7oQ8AgQr7Vskruiud0q6TI',
    appId: '1:218821411512:ios:146e2c4c1fc3179024ea4d',
    messagingSenderId: '218821411512',
    projectId: 'mychatapp-522bc',
    storageBucket: 'mychatapp-522bc.appspot.com',
    iosClientId: '218821411512-m490mgfvue7p7kc3cnpsaribhfee5vn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwf8QOxJmZO7oQ8AgQr7Vskruiud0q6TI',
    appId: '1:218821411512:ios:146e2c4c1fc3179024ea4d',
    messagingSenderId: '218821411512',
    projectId: 'mychatapp-522bc',
    storageBucket: 'mychatapp-522bc.appspot.com',
    iosClientId: '218821411512-m490mgfvue7p7kc3cnpsaribhfee5vn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
